### ISSUE TITLE
For fetched data, I can additionally clean the data to include/exclude rows

### ISSUE THREAD

**Issue by KevinFrazier** [plependu/RCHI#32]
Description:
fetched data type -> list<json>
output of functions -> a new list<json>

Functions that we need:
**-Filter (list<json>, index, value)** 
/*
Example:

data = [
    {
        "id": "1",
        "category": "Total",
        "subpopulation": "Individuals",
        "total": 766
    },
    {
        "id": "2",
        "category": "Age",
        "subpopulation": "Adults",
        "total": 484
    },
]

newList = Filter(data, "Age", "Adults") //removes id:"2"

*/

**-Combine (list<json>, list2<json>)**
/*
combines 2 json lists given that they are from the same table
*/

**Comment by jwlee64** [comment]
Just confirming, 
- for combine, we remove entries with identical ids (would only happen if they were identical entries because they are from the same original list)
- for filter, we do not modify id, because of the reason above ( id should not affect behavior if there are gaps)

And some questions,
- this ->  newList = Filter(data, "Age", "Adults")  does not follow 
  this -> Filter (list, index, value)
  Would it be better to implement both? or standerdize filter function?
- What does index do? would it remove a range?

**Comment by jwlee64** [comment]
Also,
- is the input type a list or the fetched data type?
- can i create a toList function (theres probably one out there already)?
- And then just do in list to list for my functions?
